#define __STDC__ 1
#define __STDC_VERSION__ 199901L
#define __STDC_HOSTED__ 1
#define __STDC_ISO_10646__ 200607
#define __EDG__ 1
#define __EDG_VERSION__ 407
#define __EDG_SIZE_TYPE__ unsigned int
#define __EDG_PTRDIFF_TYPE__ int
#define __sizeof_int 4
#define __sizeof_long 4
#define __sizeof_ptr 4
#define __ARMCC_VERSION 5060960
#define __TARGET_CPU_CORTEX_M4_FP_SP 1
#define __TARGET_FPU_VFPV4_SP_D16 1
#define __MICROLIB 1
#define __UVISION_VERSION 536
#define _RTE_ 1
#define NRF52 1
#define CONFIG_GPIO_AS_PINRESET 1
#define FLOAT_ABI_HARD 1
#define NRF52832_XXAA 1
#define NRF52_PAN_74 1
#define NRF_SD_BLE_API_VERSION 6
#define S132 1
#define SOFTDEVICE_PRESENT 1
#define SWI_DISABLE0 1
#define __HEAP_SIZE 10240
#define __STACK_SIZE 10240
#define BOARD_AMPM_GT999 1
#define DEBUG 1
#define BOARD_SOS 1
#define USE_MESH 1
#define USE_BLE 1
#define BENKON_HW_V3 1
#define __CC_ARM 1
#define __arm 1
#define __arm__ 1
#define __TARGET_ARCH_7E_M 1
#define __TARGET_ARCH_ARM 0
#define __TARGET_ARCH_THUMB 4
#define __TARGET_ARCH_A64 0
#define __TARGET_ARCH_AARCH32 1
#define __TARGET_PROFILE_M 1
#define __TARGET_FEATURE_HALFWORD 1
#define __TARGET_FEATURE_THUMB 1
#define __TARGET_FEATURE_MULTIPLY 1
#define __TARGET_FEATURE_DSPMUL 1
#define __TARGET_FEATURE_DOUBLEWORD 1
#define __TARGET_FEATURE_DIVIDE 1
#define __TARGET_FEATURE_UNALIGNED 1
#define __TARGET_FEATURE_CLZ 1
#define __TARGET_FEATURE_DMB 1
#define __TARGET_FPU_VFPV4 1
#define __TARGET_FPU_VFP 1
#define __TARGET_FPU_VFP_SINGLE 1
#define __TARGET_FEATURE_EXTENSION_REGISTER_COUNT 16
#define __APCS_INTERWORK 1
#define __FP_FAST_FMAF 1
#define __thumb 1
#define __thumb__ 1
#define __t32__ 1
#define __OPTIMISE_SPACE 1
#define __OPTIMISE_LEVEL 0
